version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "daily"
    target_branch: "master"
    default_labels:
      - "dependencies"
      - "wait_for_review"
    ignored_updates:
      - match:
          dependency_name: "google.golang.org/grpc"
      - match:
          dependency_name: "github.com/uber/jaeger-client-go"

